# Gradle JVM 性能与内存配置
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# AndroidX 支持与轻量 R 文件优化
android.useAndroidX=true
android.nonTransitiveRClass=true

# 构建性能加速：开启多任务并行与构建缓存
org.gradle.parallel=true
org.gradle.caching=true
kotlin.incremental=true

# 代码风格规范
kotlin.code.style=official
